// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "DataClient": ModelProvider Resource Client
//
// Command:
// $ goagen
// --design=ModelProvider/design
// --out=$(GOPATH)\src\ModelProvider
// --version=v1.3.1

package client

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
	"strconv"
)

// AskDataModelProviderPath computes a request path to the askData action of ModelProvider.
func AskDataModelProviderPath(hash string, eTHKey string, transID int) string {
	param0 := hash
	param1 := eTHKey
	param2 := strconv.Itoa(transID)

	return fmt.Sprintf("/model/askData/%s/%s/%s", param0, param1, param2)
}

// ask for data
func (c *Client) AskDataModelProvider(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewAskDataModelProviderRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewAskDataModelProviderRequest create the request corresponding to the askData action endpoint of the ModelProvider resource.
func (c *Client) NewAskDataModelProviderRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("POST", u.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}

// UploadModelProviderPath computes a request path to the upload action of ModelProvider.
func UploadModelProviderPath(hash string, eTHKey string, hEKey string, rSAKey string) string {
	param0 := hash
	param1 := eTHKey
	param2 := hEKey
	param3 := rSAKey

	return fmt.Sprintf("/model/upload/%s/%s/%s/%s", param0, param1, param2, param3)
}

// upload model
func (c *Client) UploadModelProvider(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewUploadModelProviderRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewUploadModelProviderRequest create the request corresponding to the upload action endpoint of the ModelProvider resource.
func (c *Client) NewUploadModelProviderRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("POST", u.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}

// UploadFinalModelProviderPath computes a request path to the uploadFinal action of ModelProvider.
func UploadFinalModelProviderPath(hash string, rsaKey string, transID int, eTHKey string) string {
	param0 := hash
	param1 := rsaKey
	param2 := strconv.Itoa(transID)
	param3 := eTHKey

	return fmt.Sprintf("/model/uploadFinal/%s/%s/%s/%s", param0, param1, param2, param3)
}

// upload final argument and final distance for transaction ID
func (c *Client) UploadFinalModelProvider(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewUploadFinalModelProviderRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewUploadFinalModelProviderRequest create the request corresponding to the uploadFinal action endpoint of the ModelProvider resource.
func (c *Client) NewUploadFinalModelProviderRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("POST", u.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}
