// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "DataClient": Application User Types
//
// Command:
// $ goagen
// --design=ModelProvider/design
// --out=$(GOPATH)\src\ModelProvider
// --version=v1.3.1

package client
